# Generated by Django 3.2.16 on 2022-12-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
